version: '3.8'

services:
  vulnlearnai:
    build: .
    container_name: vulnlearnai_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data/model:/app/data/model
      - ./data/logs:/app/data/logs
      - ./data/training_data.json:/app/data/training_data.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
